### PR TITLE
Adding the new service definition for target queries.

### PR DESCRIPTION
**Pull request by thilinamb**
The protocol buffer service definition for target queries. It includes how predicates are defined, combined into expressions, and the message formats for requests and responses.

**Service host:** Each DHT node
**Invoker:** We may introduce a separate query servers who will initiate these queries. The consumers (e.g.: visualization system) may send a request to the query server which will in-turn query the DHT. Then it will aggregate the responses and send it to the consumer. 

The service is designed having future requirements in mind such as feature and metadata based predicates.

### CODE REVIEW

**Review by kevin-bruhwiler — COMMENTED** [review]
It looks fairly straightforward. I have two questions. What are metadataPredicates? Are they contained within featurePredicates, or are they something else?

In the MatchingStrand message, what are fromTS and toTS? Temporal scopes? Are strands divided both spatially and temporally?

**Comment by millardk** [comment]
How will spacial scopes be specified? Constructing a box using lattitude and longitude and the comparison operators? Could we add a bounding box comparison and a bounding box value? Or perhaps a within distance comparison operator and a position value?

**Comment by millardk** [comment]
> In the MatchingStrand message, what are fromTS and toTS? Temporal scopes? Are strands divided both spatially and temporally?

I somewhat agree with this, only one TS value needs to be transmitted as long as the recipient knows the schema.

**Review by millardk — APPROVED** [review]

**Comment by kevin-bruhwiler** [comment]
> How will spacial scopes be specified? Constructing a box using lattitude and longitude and the comparison operators? Could we add a bounding box comparison and a bounding box value? Or perhaps a within distance comparison operator and a position value?

I believe that we're using a list of geohashes to define the spacial scope.

**Comment by thilinamb** [comment]
> It looks fairly straightforward. I have two questions. What are metadataPredicates? Are they contained within featurePredicates, or are they something else?
> 

There are metadata attached to strands such as user and session information. Metadata predicates specified on Sessions are useful for repeated experiments. A user can set the maximum session id in a query and Sustain will ensure that it will read only the data up to and including that particular session.

> In the MatchingStrand message, what are fromTS and toTS? Temporal scopes? Are strands divided both spatially and temporally?

A strand is generated for a temporal bracket to increase the compaction rate. I was thinking including this time bracket may be useful when supporting temporal drill-down queries or when loading data with the same temporal locallity

**Comment by thilinamb** [comment]
> > In the MatchingStrand message, what are fromTS and toTS? Temporal scopes? Are strands divided both spatially and temporally?
> 
> I somewhat agree with this, only one TS value needs to be transmitted as long as the recipient knows the schema.

Did you mean derive the other timestamp based on the temporal bracket info. stored in the schema?

**Comment by thilinamb** [comment]
> > How will spacial scopes be specified? Constructing a box using lattitude and longitude and the comparison operators? Could we add a bounding box comparison and a bounding box value? Or perhaps a within distance comparison operator and a position value?
> 
> I believe that we're using a list of geohashes to define the spacial scope.

Yes. The query server may support other spatial scopes (such as bounding boxes) and it will convert them to a set of geohashes. Because at individual dht nodes, the data is organized based on geohashes.

**Review by kevin-bruhwiler — APPROVED** [review]

**Pull request merged**
